language: go

script:
  - go get github.com/mitchellh/gox
  - gox -osarch="linux/386 linux/amd64 darwin/amd64 windows/amd64" -output="out/{{.Dir}}-{{.OS}}-{{.Arch}}"
# linux/386 linux/amd64 linux/arm darwin/amd64 darwin/386 windows/amd64 windows/386

deploy:
  - provider: bintray
    file: bintray-bin.json
    user: suntong
    key: ${BINTRAY_API_KEY}
